<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use App\Models\Book;
use Carbon\Carbon;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable FK checks safely
        Schema::disableForeignKeyConstraints();

        // Truncate books table
        DB::table('books')->truncate();

        // Re-enable FK checks
        Schema::enableForeignKeyConstraints();

        $now = Carbon::now();

        $books = collect([
            [
                'title' => 'Writer\'s Choice',
                'author' => null,
                'genre' => 'English/Language Arts Textbook',
                'published_year' => 1996,
                'availability' => 2,
            ],
            [
                'title' => 'The American Democracy',
                'author' => 'Thomas Patterson',
                'genre' => 'Political Science',
                'published_year' => 2005,
                'availability' => 1,
            ],
		 [
                'title' => 'Settling Manila',
                'author' => 'PAISA Int\'l, Inc.',
                'genre' => 'Historical/Informational Text',
                'published_year' => 1993,
                'availability' => 1,
            ],
            [
                'title' => 'Scientific Research',
                'author' => null,
                'genre' => 'Research Methodology/Science',
                'published_year' => 2004,
                'availability' => 1,
            ],
            [
                'title' => 'The War on Drugs',
                'author' => 'Neal Bernards',
                'genre' => 'Historical/Political',
                'published_year' => 1991,
                'availability' => 1,
            ],
            [
                'title' => 'Cauldron of Turmoil',
                'author' => 'Barry Rubin',
                'genre' => 'History',
                'published_year' => 1992,
                'availability' => 1,
            ],
            [
                'title' => 'i3n Español',
                'author' => 'Estella Gahala, Patricia Hamilton Carlin, Audrey L. Hiening-Boynton, Ricardo Otheguy and Barbara Rupert',
                'genre' => 'Educational Academic',
                'published_year' => 2004,
                'availability' => 1,
            ],
            [
                'title' => 'American History the Early Years to 1877 (Section Quizzes)',
                'author' => 'Donald A. Ritchie, Albert S. Broussard',
                'genre' => 'Educational/Academic',
                'published_year' => null,
                'availability' => 1,
            ],
            [
                'title' => 'A Garrison State in the Make and Other Speeches',
                'author' => 'Benigno "Ninoy" S. Aquino Jr.',
                'genre' => 'History',
                'published_year' => 1985,
                'availability' => 1,
            ],
            [
                'title' => 'Welcome to my Country (KENYA)',
                'author' => 'Roseline Ngcheong-Lum/Victoria Derr',
                'genre' => 'Informational/Educational',
                'published_year' => 2000,
                'availability' => 1,
            ],
            [
                'title' => 'Welcome to my Country (CHINA)',
                'author' => 'Goh Sui Noi/Lim Bee Ling',
                'genre' => 'Informational/Educational',
                'published_year' => 1999,
                'availability' => 1,
            ],
            [
                'title' => 'Nations of Nations',
                'author' => 'James West Davidson, William E. Gienap, Christine Leigh Heyrman, Mark H. Lytle and Michael B. Stoff',
                'genre' => 'History/Educational Textbook',
                'published_year' => 2005,
                'availability' => 1,
            ],
            [
                'title' => 'Children of the Incas',
                'author' => 'David Mangurian',
                'genre' => 'History/Informational/Educational',
                'published_year' => 1979,
                'availability' => 1,
            ],
            [
                'title' => 'American Popular Music',
                'author' => 'Larry Starr and Christopher Waterman',
                'genre' => 'Music History',
                'published_year' => 2007,
                'availability' => 1,
            ],
            [
                'title' => 'Reading West Virginia',
                'author' => 'J. David Cooper and John J. Pikulski',
                'genre' => 'Educational/Social Studies',
                'published_year' => 2007,
                'availability' => 1,
            ],
            [
                'title' => 'Grammar Workbook',
                'author' => null,
                'genre' => 'English/Language Learning',
                'published_year' => 1996,
                'availability' => 2,
            ],
            [
                'title' => 'The Cinema of Manuel Conde',
                'author' => 'Nicanor G. Tiongson',
                'genre' => 'Literature/Cultural History',
                'published_year' => 2008,
                'availability' => 1,
            ],
            [
                'title' => 'On LEIBNIZ',
                'author' => 'Nicholas Rescher',
                'genre' => 'Philosophy/History',
                'published_year' => 2003,
                'availability' => 1,
            ],
            [
                'title' => 'Children\'s Illustrated Dictionary',
                'author' => 'John Grisewood, Neil Morris and Ting Morris',
                'genre' => 'Reference/Educational',
                'published_year' => 1999,
                'availability' => 1,
            ],
            [
                'title' => 'Potentially Viable Small Enterprises in the Philippines',
                'author' => null,
                'genre' => 'Business/Entrepreneurship/Economics',
                'published_year' => 1987,
                'availability' => 1,
            ],
            [
                'title' => 'Paradox and Discovery',
                'author' => 'Arthur J. Minton and Thomas A. Shipka',
                'genre' => 'Philosophy/Science',
                'published_year' => 1982,
                'availability' => 1,
            ],
            [
                'title' => 'United State Adventure in Time and Place',
                'author' => 'Dr. James A. Banks, Dr. Barry K. Beyer, Dr. Gloria Contreras, Jean Craven, Dr. Gloria Ladson-Billings, Dr. Mary A. MacFarland and Dr. Walter C. Parker',
                'genre' => 'History/Social Studies',
                'published_year' => 1997,
                'availability' => 4,
            ],
            [
                'title' => 'The American Journey Building A Nation',
                'author' => 'Joyce Appleby, Ph. D., Alan Brinkley, Ph. D. and James McPherson, Ph. D.',
                'genre' => 'History/Social Studies',
                'published_year' => 2000,
                'availability' => 2,
            ],
            [
                'title' => 'Taking Sides United States History Vol. 1 The Colonial Period to Reconstruction',
                'author' => 'Larry Madaras and James M. SoRelle',
                'genre' => 'History',
                'published_year' => 2008,
                'availability' => 0,
            ],
            [
                'title' => 'Everything You Need to Know About Birth Control',
                'author' => 'Gary Mucciolo, M.D.',
                'genre' => 'Health/Informational',
                'published_year' => 1990,
                'availability' => 1,
            ],
            [
                'title' => 'Marriages & Families',
                'author' => 'David H. Olson and John DeFrain',
                'genre' => 'Social Science/Sociology',
                'published_year' => 2006,
                'availability' => 1,
            ],
            [
                'title' => 'Do It Yourself',
                'author' => 'Thomas Barnthaler',
                'genre' => 'Art',
                'published_year' => 2015,
                'availability' => 1,
            ],
            [
                'title' => 'World History the Human Experience',
                'author' => 'Mounir Farah, Ph. D., Andrea Berens Karls',
                'genre' => 'History',
                'published_year' => 1994,
                'availability' => 1,
            ],
            [
                'title' => 'World History the Human Odyssey',
                'author' => 'Jackson J. Spielvogel',
                'genre' => 'History',
                'published_year' => 1999,
                'availability' => 1,
            ],
            [
                'title' => 'Book of World Record 2005',
                'author' => 'Jenifer Corr Morse',
                'genre' => 'Reference Book',
                'published_year' => 2004,
                'availability' => 1,
            ],
            [
                'title' => 'Home Remedies a guide to symptoms and curse',
                'author' => 'Dr. Caroline Shreeve',
                'genre' => 'Health and Medicine',
                'published_year' => 2003,
                'availability' => 1,
            ],
            [
                'title' => 'Understanding Population Change',
                'author' => 'Charles B. Nam',
                'genre' => 'Social Science/Demography',
                'published_year' => 1994,
                'availability' => 1,
            ],
            [
                'title' => 'English Arts and Skills',
                'author' => 'Bro. H. Albert, F.S.C, Sis. Cornelius Julie, S.N.D., Sis. Francis Camilla, S.L., Sis. Mary Agnes, S.C., Rev\'d William McNiff, O.S.C, Rev\'d William J. Power, S.J., Sis. St. Agnes, S.S.J., Sis. M. Sylvia, S.S.J.',
                'genre' => 'Language Arts Textbook',
                'published_year' => 1971,
                'availability' => 1,
            ],
            [
                'title' => 'Reseña Veredica de la Revolucion Filipina (True Version of the Philippine Revolution)',
                'author' => 'Emilio Aguinaldo',
                'genre' => 'Historical Account/History and Politics',
                'published_year' => 2002,
                'availability' => 1,
            ],
            [
                'title' => 'Asia History, Civilization, and Culture',
                'author' => 'Joselito N. Fornier, Ph. D., Virgilio C. Galvez, Olivia M. Habana, Joseph Jay Hernando, Ma. Estela C. Banasihan, Ma. Angelica Verzosa-Ariston, Monina Olavides-Correa',
                'genre' => 'History/Cultural Studies',
                'published_year' => 2007,
                'availability' => 1,
            ],
            [
                'title' => 'Strange Worlds Amazing Places',
                'author' => null,
                'genre' => 'Geography',
                'published_year' => 1994,
                'availability' => 1,
            ],
            [
                'title' => 'Achieve Creative Experiences and Skills in Mapeh 1',
                'author' => 'Maria Carmela C. Pabalan, Stefhanie P. Teodoro, Ryan C. Gialogo and Carlo B. Bejarasco',
                'genre' => 'MAPEH Textbook',
                'published_year' => 2022,
                'availability' => 1,
            ],
            [
                'title' => 'Achieve Creative Experiences and Skills in Mapeh 5',
                'author' => 'Maria Carmela C. Pabalan, Maria Lycia Laig-Rivadelo, Lorena P. Ayongao, Carlo B. Bejarasco',
                'genre' => 'MAPEH Textbook',
                'published_year' => 2022,
                'availability' => 1,
            ],
            [
                'title' => 'Phoenix Learning Package (PLP) Skill Builders for Efficient Reading 1',
                'author' => 'Obdulia L. Jose, Evelyn S. Salazar, Dr. Araceli M. Villamin, Lourdes P. Villanueva',
                'genre' => 'Educational/Reading Skills Workbook',
                'published_year' => 2013,
                'availability' => 1,
            ],
            [
                'title' => 'Phoenix Learning Package (PLP) Skill Builders for Efficient Reading 3',
                'author' => 'Wilhelmina G. Borjal, Bernardita O. Gonzalo, Maria A. Orendain, Evelyn S. Salazar, Dr. Araceli M. Villamin',
                'genre' => 'Academic',
                'published_year' => 2014,
                'availability' => 1,
            ],
            [
                'title' => 'Phoenix Learning Package (PLP) Skill Builders for Efficient Reading 4',
                'author' => 'Wilhelmina G. Borjal, Maria A. Orendain, Evelyn S. Salazar and Dr. Araceli M. Villamin',
                'genre' => 'Academic',
                'published_year' => 2014,
                'availability' => 1,
            ],
            [
                'title' => 'The 21st Century Mapeh in Action',
                'author' => 'Ligaya Bautista Garcia-Quinitio, Eduardo V. Cipriano, Eliseo P. Buhain, Juliet H. Brioso, Diana Alcoba-Lacia, Almira Alcoba-Alonzo, Gernalyn Andres-Solano',
                'genre' => 'Textbook/Educational/Academic Workbook',
                'published_year' => 2016,
                'availability' => 1,
            ],
            [
                'title' => 'Enjoying Life Through Music, Art, Physical Education, And Health',
                'author' => 'Marissa C. Pascual, Agnes C. Friginal, Ma. Mignon C. Artuz',
                'genre' => 'Textbook/Educational/Instructional/Academic',
                'published_year' => 2014,
                'availability' => 1,
            ],
            [
                'title' => 'The Phoenix World of Reading 3',
                'author' => 'Elisa M. Robles and Vivien R. Avelino',
                'genre' => 'Academic',
                'published_year' => 2017,
                'availability' => 1,
            ],
            [
                'title' => 'The Phoenix World of Reading 6',
                'author' => 'Valerie C. Bacasmas, Rachel S. Villafuerte and Victoria L. Magbag',
                'genre' => 'Academic',
                'published_year' => 2017,
                'availability' => 1,
            ],
            [
                'title' => 'Pilipinas Lupang Hinirang',
                'author' => 'Ethel Halal-Estrella, Ruben Maraviles Milambiling',
                'genre' => 'Music/Poetry',
                'published_year' => 1999,
                'availability' => 1,
            ],
            [
                'title' => 'Business Finance',
                'author' => 'Florenz C. Tugas, Aeson Luiz C. Dela Cruz, Alloysius Joshua S. Paril, Alger C. Tang',
                'genre' => 'Business Studies',
                'published_year' => 2017,
                'availability' => 1,
            ],
            [
                'title' => 'Fundamentals of Voice & Articulation',
                'author' => 'Lyle V. Mayer',
                'genre' => 'Instructional/Reference',
                'published_year' => 1996,
                'availability' => 1,
            ],
            [
                'title' => 'Beginning Reading Phonics',
                'author' => 'Elisie T. Torreno, Carolina T. Tirona, Dalrose Ann C. Sambo',
                'genre' => 'Instructional/Workbook/Skill Builder',
                'published_year' => 2004,
                'availability' => 1,
            ],
            [
                'title' => 'Moving on with Reading and Phonics',
                'author' => 'Elisie T. Torreno, Julianna C. Macayan, Carolina T. Tirona, Dalrose Ann C. Sambo',
                'genre' => 'Instructional/Workbook/Skill Builder',
                'published_year' => 2004,
                'availability' => 1,
            ],
            ['title' => 'Road to Writing and Composition 2', 'author' => 'Paquito Badayos, Ph. D.', 'genre' => 'Instructional/Workbook', 'published_year' => '2003', 'availability' => 2],
            ['title' => 'Effective Writing', 'author' => 'Unice Lazarte-Apostol', 'genre' => 'Reference/Educational/Instructional textbook', 'published_year' => '2009', 'availability' => 1],
            ['title' => 'Bagong Bisyon, Bagong Misyon Pambansang Dambana ni Lolo Uweng ng Landayan', 'author' => 'Sonny A. Ordoña', 'genre' => 'Literature/Cultural/Local History', 'published_year' => '2022', 'availability' => 1],
            ['title' => 'Essentials of Contemporary Philippine Arts from the Regions', 'author' => 'Shaun Michael G. Marasigan', 'genre' => 'Educational/Academic Textbook', 'published_year' => '2023', 'availability' => 1],
            ['title' => 'Give Me Liberty an American History', 'author' => 'Eric Foner', 'genre' => 'History', 'published_year' => '2005', 'availability' => 1],
            ['title' => 'Radiance Worktext in Music, Arts, Physical Education, and Health', 'author' => 'Jocelyn L. Lagarto, Baby Jinky N. Sinugbuhan, Roel G. Lodrino, Alvin L. Banlaygas, Melanie I. Cruz, Leilani L. Angeles', 'genre' => 'MAPEH', 'published_year' => '2015', 'availability' => 1],
            ['title' => 'Comprehensive Curriculum of Basic Skills', 'author' => 'Garret Christopher, Bonita Rio Ferraro, Barbara Reeves', 'genre' => 'Instructional/Educational workbook', 'published_year' => '1993', 'availability' => 1],
            ['title' => 'The Alamo', 'author' => 'Leonard Everett Fisher', 'genre' => 'Historical Nonfiction', 'published_year' => '1985', 'availability' => 1],
            ['title' => 'Fourth Asian Regional Conference in Biological Education', 'author' => 'University of the Philippines Science Education Center', 'genre' => 'Biology/Science', 'published_year' => '1972', 'availability' => 1],
            ['title' => 'Pasajes Cultura', 'author' => 'Mary Lee Bretz, Trisha Dvorak, Carl Kirschner', 'genre' => 'Culture/Language', 'published_year' => '2002', 'availability' => 1],
            ['title' => 'Exploring Life Through Science Series: General Physics 2', 'author' => 'Angeline A. Silverio', 'genre' => 'Science', 'published_year' => '2017', 'availability' => 1],
            ['title' => 'Exploring Life Through Science Series: Physics Third Edition', 'author' => 'Angeline A. Silverio', 'genre' => 'Science', 'published_year' => '2019', 'availability' => 1],
            ['title' => 'Media Trends Importance of New Media Technology to Modern Filipinos', 'author' => 'Ligaya Hidalgo, Mattheus A. Mopera', 'genre' => 'Communication and Media Studies/Eduactional/Academic', 'published_year' => '2015', 'availability' => 1],
            ['title' => 'Discovering Information Technology and Microsoft Office 2010 Level 1', 'author' => 'Divakar Bagari and Pedmer Cezar F. Ferrancullo', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2011', 'availability' => 1],
            ['title' => 'Keyboarding with Computer Applications', 'author' => 'Johnson, Chiri, Cotton and Stanley', 'genre' => 'Skill-development/Educational/Textbook', 'published_year' => '2004', 'availability' => 1],
            ['title' => 'California Vistas Ancient Civilizations', 'author' => 'Jackson J. Spielvogel, Ph. D., et al.', 'genre' => 'History', 'published_year' => '2007', 'availability' => 1],
            ['title' => 'A Century of Philippine Legislature', 'author' => 'Manuel D. Duldulao', 'genre' => 'History', 'published_year' => '2007', 'availability' => 1],
            ['title' => 'Capturing Nature in Watercolor', 'author' => 'Philip Jamison', 'genre' => 'History', 'published_year' => '1980', 'availability' => 1],
            ['title' => 'Assembly of the Nation A Centennial History of the House of Representative of the Philippines', 'author' => 'Manuel L. Quezon III, et al.', 'genre' => 'History', 'published_year' => '2007', 'availability' => 1],
            ['title' => 'Guerra De Filipinas', 'author' => 'The National Historical Institute', 'genre' => 'History', 'published_year' => '2007', 'availability' => 1],
            ['title' => 'Sanghaya 2005 (Philippine Arts and Culture Yearbook)', 'author' => 'Adelfa M.P. Dela Fuente', 'genre' => 'Cultural Studies/Reference', 'published_year' => '2005', 'availability' => 1],
            ['title' => 'A taste of Chicken Soup for the Couple’s Soul', 'author' => 'Jack Canfield, et al.', 'genre' => 'Literature/Anthology/Collection of Stories', 'published_year' => '2006', 'availability' => 1],
            ['title' => 'Holiday Magazine Guide to Israel', 'author' => 'Random House Inc.', 'genre' => 'Geography, Hospitality, tourism And Cultural Studies', 'published_year' => '1971', 'availability' => 1],
            ['title' => 'Balangkas A resource Book on the Care of Built Heritage in the Philippines', 'author' => 'National Commission for Culture and the Arts (NCAA)', 'genre' => 'Tourism Culture and the Arts', 'published_year' => '2007', 'availability' => 1],
            ['title' => 'Discovery Guide Take Charge', 'author' => 'Franklin Covey Co.', 'genre' => 'Student Educational Curriculum/Educational', 'published_year' => '', 'availability' => 1],
            ['title' => 'The best of Casual Mediterranean Cooking TAVERNA', 'author' => 'Joyce Goldstein', 'genre' => 'Cookbook', 'published_year' => '1996', 'availability' => 1],
            ['title' => 'The Pasta Cookbook', 'author' => 'Carole Handslip', 'genre' => 'Cookbook', 'published_year' => '1979', 'availability' => 1],
            ['title' => 'Mapping the Earth Mapping Life', 'author' => 'Ponciano L. Bennagen and Antoinette G. Royo', 'genre' => 'Social Science/Environmental Studies', 'published_year' => '2000', 'availability' => 1],
            ['title' => 'World History', 'author' => 'Josefa L. Quirante Radford', 'genre' => 'History', 'published_year' => '1986', 'availability' => 1],
            ['title' => 'LOTUS 1-2-3 Simplified for the IBM Personal Computer', 'author' => 'Don Cassel', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1986', 'availability' => 1],
            ['title' => 'Central Banking for every Juan and Maria', 'author' => 'Ignacio R. Bunye', 'genre' => 'Economics, Finance', 'published_year' => '2011', 'availability' => 1],
            ['title' => 'Traditions Encounters A Global Perspective on the Past', 'author' => 'Jerry H. Bentley and HerbertF. Ziegler', 'genre' => 'History/Geography', 'published_year' => '2006', 'availability' => 1],
            ['title' => 'Gourmet: The Magazine of Good Living', 'author' => '', 'genre' => 'Food and Lifestyle Magazine', 'published_year' => '1995', 'availability' => 1],
            ['title' => 'Crocodile Attack in Australia', 'author' => 'Hugh Edwards', 'genre' => 'Wildlife Adventure, Zoology/Environmental Studies', 'published_year' => '1988', 'availability' => 1],
            ['title' => 'Native Americans', 'author' => 'Spring/Summer', 'genre' => 'Non-Fiction, History and Culture', 'published_year' => '2002', 'availability' => 1],
            ['title' => 'Historical Markers: Metropolitan Manila', 'author' => 'The National Historical Institute', 'genre' => 'History', 'published_year' => '1999', 'availability' => 1],
            ['title' => 'Wonders of Learning: Seven Wonders', 'author' => 'WS Pacific Publications, Inc.', 'genre' => 'History, Geography and World Heritage', 'published_year' => '2008', 'availability' => 1],
            ['title' => 'Gregg Shorthand: For the Administrative Assistant', 'author' => 'Charles Zoubek', 'genre' => 'Educational/Reference Genre', 'published_year' => '1990', 'availability' => 1],
            ['title' => 'Hiyas ng Wika: Binagong Edisyon', 'author' => 'Dr. Ester R. Madriaga and Amelia M. Cabuslay', 'genre' => 'Filipino (Language & Literature', 'published_year' => '1982', 'availability' => 1],
            ['title' => 'Instructors Guide for Computers and Applications', 'author' => 'Marilyn Meyers', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1986', 'availability' => 1],
            ['title' => 'Aries SERVER+ Certified Technician', 'author' => 'Leonard Lev, Robert Peterson and Tina Canedo', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2003', 'availability' => 1],
            ['title' => 'Desktop Typography with QuarkXPress', 'author' => 'Frank J. Romano', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1992', 'availability' => 1],
            ['title' => 'Programing by Design: A first Course in Structured Programming', 'author' => 'Phillip L. Miller and Lee W. Miller', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1987', 'availability' => 1],
            ['title' => 'Learning to Use WORDSTAR 3.3: An Introduction', 'author' => 'Gary B. Shelly and Thomas J. Cashman', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1986', 'availability' => 1],
            ['title' => 'Exploring ICT MS Office: Advance', 'author' => 'Computer Assisted Learning Corporation', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2018', 'availability' => 1],
            ['title' => 'Exploring ICT MS Office: Intermediate', 'author' => 'Computer Assisted Learning Corporation', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2017', 'availability' => 1],
            ['title' => 'My Computer: Microsoft Access XP', 'author' => 'ABIVA Publishing House, Inc.', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2008', 'availability' => 1],
            ['title' => 'My Computer: Microsoft Visual Basic 6.0', 'author' => 'ABIVA Publishing House, Inc.', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2008', 'availability' => 1],
            ['title' => 'My Computer: Microsoft Powerpoint XP', 'author' => 'ABIVA Publishing House, Inc.', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2008', 'availability' => 1],
            ['title' => 'Broadcasting, Cable, The Internet and Beyond', 'author' => 'Joseph R. Dominic, Fritz Messere and Barry Sherman', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2004', 'availability' => 1],
            ['title' => 'Connect Online: Web Learning Adventure', 'author' => 'Gwen Solomon and Lynne Schrum', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2003', 'availability' => 3],
            ['title' => 'Tk Solver Plus: Introduction Manual', 'author' => 'Universal Technical Systems, Inc.', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1987', 'availability' => 4],
            ['title' => 'MC 68000: Assembly Language and Systems Programming', 'author' => 'William Ford and William Topp', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1988', 'availability' => 2],
            ['title' => 'PC Tools 7 Made Easy', 'author' => 'Bryan Pfaffenberger', 'genre' => 'Software Guide/Computer/Technology', 'published_year' => '1991', 'availability' => 1],
            ['title' => 'Operating System', 'author' => 'Stuart E. Madnick and John J. Donovan', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1974', 'availability' => 1],
            ['title' => 'Using Computers 2nd Edition', 'author' => 'D. G. Dologite and R. J. Mockler', 'genre' => 'Computer Science/Information Technology', 'published_year' => '1989', 'availability' => 1],
            ['title' => 'Excel a Comprehensive Approach 2002 Core & Expert', 'author' => 'Kathleen Stewart', 'genre' => 'Computer Applications/Software Training', 'published_year' => '2002', 'availability' => 1],
            ['title' => 'Using Software Tools Word Star 4.0', 'author' => 'Laura Saret and Peter Dublin', 'genre' => 'Educational/Technical', 'published_year' => '1988', 'availability' => 2],
            ['title' => 'Glencoe: Keyboarding with Computer Applications Lessons 1-80', 'author' => 'Jack E. Johnson, Ph.D., et al.', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '2004', 'availability' => 2],
            ['title' => 'The Little System: 7.1/7.5 Book', 'author' => 'Kay Yarborough Nelson', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1994', 'availability' => 1],
            ['title' => 'Quattro', 'author' => 'Timothy J. O’Leary, et al.', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1992', 'availability' => 1],
            ['title' => 'Storyboard Manual', 'author' => 'Dorotea A. Valdes', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1991', 'availability' => 1],
            ['title' => 'Guiding Youth Careers: A Handbook', 'author' => 'International Labour Organizations', 'genre' => 'Educational/Career Guidance and Counseling', 'published_year' => '2007', 'availability' => 1],
            ['title' => 'Introduction to Information Technology and OPENOFFICE.ORG', 'author' => 'Charmagne Mun', 'genre' => 'Educational/Academic/Instructional Guide', 'published_year' => '2009', 'availability' => 1],
            ['title' => 'An Introduction: Framework III', 'author' => 'Bill Harrison', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1988', 'availability' => 1],
            ['title' => 'The Osborne/McGraw-Hill: Guide to IBM PC Communications', 'author' => 'David kruglinski', 'genre' => 'Educational/Technology/ Computer Manual', 'published_year' => '1984', 'availability' => 1],
            ['title' => 'Science a Closer Look Second Edition', 'author' => 'Dr. Jay K. Hackett, et al.', 'genre' => 'Science', 'published_year' => '2011', 'availability' => 2],
            ['title' => 'Glencoe Science Voyages: Laboratory Manual Student Edition', 'author' => 'McGraw-Hill Companies', 'genre' => 'Academic/Educational/Laboratory Manual', 'published_year' => '', 'availability' => 1],
            ['title' => 'Cyber Science.rev: Worktext in Science and Technology', 'author' => 'Myrna Quilang-Adduru, Ph.D.', 'genre' => 'Science', 'published_year' => '2018', 'availability' => 1],
            ['title' => 'Science Links: Worktext in Science and Health for Grade Five', 'author' => 'Evelyn T. Larisma, et al.', 'genre' => 'Science', 'published_year' => '2010', 'availability' => 1],
            ['title' => 'The Anatomy Coloring Book', 'author' => 'Wynn Kapit and Lawrence M. Elson', 'genre' => 'Educational/Activity Book/Academic', 'published_year' => '1993', 'availability' => 1],
            ['title' => 'Science and Technology for the Modern WORLD', 'author' => 'Marlene M. Gutierrez', 'genre' => 'Science and Technology', 'published_year' => '1999', 'availability' => 1],
            ['title' => 'Science in our World', 'author' => 'Norma M. Abracia, Ed.D., et al.', 'genre' => 'Science', 'published_year' => '2014', 'availability' => 1],
            ['title' => 'Science and Health Activity Book', 'author' => 'Mila G. Agda, et al.', 'genre' => 'Academic/Educational Workbook', 'published_year' => '2001', 'availability' => 1],
            ['title' => 'Living with Science Kinder', 'author' => 'Melody O. Basa', 'genre' => 'Science', 'published_year' => '1990', 'availability' => 1],
            ['title' => 'Science Power', 'author' => 'Nenita Asuncion-Apolinario and Ethel Grace Apolinarion-Ramos', 'genre' => 'Science', 'published_year' => '2007', 'availability' => 1],
            ['title' => 'Practical Science 7: Teacher’s Manuel', 'author' => 'Eduard Christian R. Papa, et al.', 'genre' => 'Science', 'published_year' => '2018', 'availability' => 1],
            ['title' => 'Practical Science 7', 'author' => 'Eduard Christian R. Papa, et al.', 'genre' => 'Science', 'published_year' => '2018', 'availability' => 1],
            ['title' => 'Practical Science 8: Teacher’s Manual', 'author' => 'Eduard Christian R. Papa, et al.', 'genre' => 'Science', 'published_year' => '2018', 'availability' => 1],
            ['title' => 'Practical Science 8', 'author' => 'Eduard Christian R. Papa, et al.', 'genre' => 'Science', 'published_year' => '2018', 'availability' => 2],
            ['title' => 'Practical Science 9: Teacher’s Manual', 'author' => 'Eduard Christian R. Papa, et al.', 'genre' => 'Science', 'published_year' => '2018', 'availability' => 1],
            ['title' => 'Practical Science 9', 'author' => 'Mary Grace F. Pineda, et al.', 'genre' => 'Science', 'published_year' => '2018', 'availability' => 2],
            ['title' => 'Discover Science 7: Teacher’s Guidebook', 'author' => 'Ian Mark F. Allas, et al.', 'genre' => 'Science', 'published_year' => '2013', 'availability' => 2],
            ['title' => 'Discover Science 8: Teacher’s Guidebook', 'author' => 'Ian Mark F. Allas, et al.', 'genre' => 'Science', 'published_year' => '2013', 'availability' => 2],
            ['title' => 'Discover Science 9: Teacher’s Guidebook', 'author' => 'Ian Mark F. Allas, et al.', 'genre' => 'Science', 'published_year' => '2014', 'availability' => 1],
            ['title' => 'Discover Science 9', 'author' => 'Ian Mark F. Allas, et al.', 'genre' => 'Science', 'published_year' => '2014', 'availability' => 1],
            ['title' => 'Sociology: Third Edition', 'author' => 'Rodney Stark', 'genre' => 'Social Science', 'published_year' => '1989', 'availability' => 3],
            ['title' => 'Modern Earth Science', 'author' => 'William L. Ramsey and Raymond A. Burckley', 'genre' => 'Science', 'published_year' => '1965', 'availability' => 1],
            ['title' => 'Energy and the Way We Live', 'author' => 'Melvin Kranzberg, et al.', 'genre' => 'Educational/Science', 'published_year' => '1980', 'availability' => 3],
            ['title' => 'Student Activity Workbook: Entrepreneurship', 'author' => 'Earl C. Meyer, Ph.D. and Kathleen R. Allen, Ph.D.', 'genre' => 'Business Economics', 'published_year' => '1994', 'availability' => 1],
            ['title' => 'Business Basic Third Edition', 'author' => 'Robert J. Bent and George C. Sethares', 'genre' => 'Business & Economic', 'published_year' => '1988', 'availability' => 1],
            ['title' => 'New Business Ventures and the Entrepreneur 6th Edition', 'author' => 'Michael J. Roberts, et al.', 'genre' => 'Academic Textbook/Entrepreneurship Guide', 'published_year' => '2006', 'availability' => 1],
            ['title' => 'Essentials of Business Communication', 'author' => 'Mary Allen Guffey', 'genre' => 'Business & Economics', 'published_year' => '1998', 'availability' => 1],
            ['title' => 'Basic Business: Basic Using the Apple', 'author' => 'Peter Mears and Louis Raho', 'genre' => 'Busines & Economics', 'published_year' => '1986', 'availability' => 1],
            ['title' => 'Money and the Economy Third Edition', 'author' => 'John J. Klien', 'genre' => 'Business & economics', 'published_year' => '1974', 'availability' => 1],
            ['title' => 'An Introduction to Business and Management 2nd Edition', 'author' => 'Monico H. Ignacio', 'genre' => 'Business and Management', 'published_year' => '1977', 'availability' => 1],
            ['title' => 'Quantitative Approaches to Management', 'author' => 'Richard I. Levin, et al.', 'genre' => 'Business and Management', 'published_year' => '1982', 'availability' => 1],
            [
                'title' => 'Productivity Management',
                'author' => 'Joseph Prokopenko',
                'genre' => 'Business & Management',
                'published_year' => 1987,
                'availability' => 1,
            ],
        ])->map(function ($book) use ($now) {
            return [
                'title' => $book['title'],
                'author' => $book['author'] ?: null,
                'genre' => $book['genre'],
                'published_year' => is_numeric($book['published_year'])
                    ? (int) $book['published_year']
                    : null,
                'availability' => (int) $book['availability'],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        })->toArray();

        // Bulk insert for performance
        Book::insert($books);

        $this->command->info('📚 Books table seeded successfully!');
    }
}
